#####################################################################
# File: gui.py
# Author: Y.U.P. (yashparitkar)
# Created: 2026-07-24 Fri 19:49
# Last Modified: 2026-08-01 Sat 13:28
#
# Description: ILA Driver file
#   This file provides functions and configuration for the interface.
#   The job of the GUI is to provide a user-friendly interface to interact with
#   the ILA; it provides a staus signal (connection and status), trigger type
#   control (and/or), arm button, force trigger button allows to open a window
#   to view the captured data with either gtkwave or 
#
#   The GUI is implemented using PySide6
#
# Copyright 2026 Yash Paritkar
# SPDX-License-Identifier: CERN-OHL-P-2.0
#####################################################################

import pyside6

_libre_ila_status_codes = {
    "LIBRE_ILA_GUI_WAVEFORM_VIEWER_NOT_FOUND" : -1,
    "LIBRE_ILA_GUI_PYSIDE6_NOT_FOUND" : -2
    "LIBRE_ILA_GUI_STATUS_OK" : 0
}

# VCD viewer function ###############################################
def view_waveform(vcd_file_path):
    """
    view_waveform: This function opens user preferred waveform viewer to view the VCD file generated by the ILA.

    vcd_file_path: Path to the VCD file to be viewed.

    return: 0 if success, -1 if error
    """
    # Check if gtkwave exist
    status = exec("which gtkwave")
    if status != 0:
        print("E: gtkwave not found. Please install gtkwave to view the waveform or update the view_waveform function.")
        return _libre_ila_error_codes["LIBRE_ILA_GUI_WAVEFORM_VIEWER_NOT_FOUND"]

    # Note that we are not tracking PID of the viewer for simplicity
    command = f"gtkwave {vcd_file_path}"
    exec(command)
    return 0
############################################################